name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
env:
  IMAGE_NAME: vpn-app
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build . --file dockerfiles/dockerfile --tag $IMAGE_NAME
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_REGISTRY_LOGIN }}
      - name: push image to digitalocean
        run: |
          doctl registry login
          docker tag $IMAGE_NAME registry.digitalocean.com/vpn-app/$IMAGE_NAME
          docker push registry.digitalocean.com/vpn-app/$IMAGE_NAME
